### ISSUE TITLE
NPE when JSON language server is initialized

### ISSUE THREAD

**Issue by angelozerr** [eclipselabs/eclipse-language-service#35] opened 2016-09-29 21:39 UTC
I have the NPE when JSON language server is initialized:

```
java.lang.NullPointerException
    at org.eclipse.languageserver.LanguageServiceAccessor.getLSWrapper(LanguageServiceAccessor.java:212)
    at org.eclipse.languageserver.LanguageServiceAccessor.getLanguageServer(LanguageServiceAccessor.java:170)
    at org.eclipse.languageserver.LanguageServiceAccessor.getLSPDocumentInfoFor(LanguageServiceAccessor.java:133)
    at org.eclipse.languageserver.operations.completion.LSContentAssistProcessor.computeCompletionProposals(LSContentAssistProcessor.java:41)
    at org.eclipse.ui.genericeditor.ContentAssistProcessorRegistry$ContentAssistProcessorExtension.computeCompletionProposals(ContentAssistProcessorRegistry.java:83)
    at org.eclipse.ui.genericeditor.CompositeContentAssistProcessor.computeCompletionProposals(CompositeContentAssistProcessor.java:35)

```

After debugging, it seems the problem is because ServerCapabilities#isCodeActionProvider return null (the JSON server return noen value for that) and NPE occurs when you do request.test(wrapper).

To fix my problem I have cathed this NPE but I'm not sure that it's a clean mean. @mickaelistria have you the same problem than me?

**Comment by mickaelistria** [comment] 2016-09-30 05:56
I don't have this issue here, completion works as expected.
However, it seems like there is a bug. At that point, I don't think it should check for ServerCapabilies.isCodeActionProvider, but rather for `ServerCapabilities.getCompletionProvider() != null`.

**Comment by mickaelistria** [comment] 2016-09-30 10:23
@angelozerr : if you have some time to check whether PR #40 fixes this issue, that'd be welcome!

**Comment by angelozerr** [comment] 2016-10-04 07:07
@mickaelistria I'm really sorry, since I have getted last version of the project, I have a lot of problems with my Target Platform and I cannot restart the project. I'm using Eclipse Jee Neon and when I use your TP it misses several plugins like EMF/Core, Commons IO, etc.

I must find time to understand what is my problem, and I will do review and ad other PR. Just find time...

**Comment by mickaelistria** [comment] 2016-10-04 07:10
@bruno-medeiros can you help with the TP ?

**Comment by bruno-medeiros** [comment] 2016-10-04 11:04
@mickaelistria As a matter of fact, I think so, I had similar problem last week trying to work with a target platform in MelnormeEclipse.  

The issue is https://github.com/eclipselabs/eclipse-language-service/blob/master/target-platform/ide.target#L11 is setup with `includeMode="slicer"` , meaning the option "Include required software" is disabled. This is what makes the problems with missing EMF/Core etc (in my case, there was also CDT stuff missing). 
The problem is that if you enable the "Include required software" option(`includeMode="planner"`) then the "http://services.typefox.io/open-source/jenkins///job/lsapi/lastSuccessfulBuild/artifact/build/p2-repository/" repo will complaing about missing gson dependency, and the whole target platform will not resolve, even though gson is in the directory "${env_var:M2_REPO}/com/google/code/gson/gson/2.5/" - but p2 doesn't understand "directory" entries, only Software Sites entries.

There is problably a way to add all required features to TP, but I couldnt be bothered figuring all that. The solution I got for Melnorme was creating a dep-repository (similar to my initial sugestion for eclipse-language-service TP) to create a p2 repo, and then have the user manually add that repository location to the target plaform (https://github.com/bruno-medeiros/MelnormeEclipse/commit/6c20e7148f0ee3ecbbffa2b75d2a87abd6524c0a ) This can't be automated AFAIK, because Software Site locations must be absolute and can't use variables. A bit annoying, but this is a temporary soluation so it's should be fine for now, until someone finally put gson 2.5 in a p2 repo. (hum.. actually that gives me an idea...)

**Comment by bruno-medeiros** [comment] 2016-10-04 11:10
... We could use Cloudbees, which offers free Jenkins hosting to OSS projects, to host our own p2 repo with gson 2.5 and whatnot. Or just ask the ls-api guys if they could include it in http://services.typefox.io/open-source/jenkins///job/lsapi/lastSuccessfulBuild/artifact/build/p2-repository/ ?

**Comment by mickaelistria** [comment] 2016-10-04 12:23
@bruno-medeiros +1. Can you please take care of asking that to ls-api folks?

**Comment by bruno-medeiros** [comment] 2016-10-04 16:39
https://github.com/TypeFox/ls-api/pull/59

**Comment by mickaelistria** [comment] 2016-10-07 09:57
@angelozerr isn't original issue fixed with https://github.com/eclipselabs/eclipse-language-service/commit/d6b136c44a6f227d30a21ec25cd9d44b1f1d5bc5 ?

**Comment by mickaelistria** [comment] 2016-10-11 11:11
The cause is https://github.com/TypeFox/ls-api/issues/63 . Capabilities are null because of the parsing error in lsp4j.

**Comment by mickaelistria** [comment] 2016-11-14 21:05
With #85 this issue seems to have vanished. Feel free to ask to reopen if this happens again.

**Closed as completed by mickaelistria** 2016-11-14 21:05 UTC
Labels: bug
