### ISSUE TITLE
Outline view is hanging UI for large data set

### ISSUE THREAD

**Issue by mniewrzal** [eclipselabs/eclipse-language-service#108] opened 2016-11-24 13:35 UTC
To reproduce:
* open Outline
* create CSS file with content (https://gist.github.com/mniewrzal/bb94772229d75774624da5436deae18e) and open

For this example file CSS language server returns 4K+ symbols.

**Comment by mickaelistria** [comment] 2016-11-25 10:36
This is most probably caused by the too naive implementation of the ContentProvider: instead of building the tree model once, about every operation runs an iterations against all elements. It makes complexity for sure O(n) for each request where it could be O(1) for a request + O(n.log(n)) on each document change

**Comment by mniewrzal** [comment] 2016-11-25 10:49
UI hangs without any modification. First attempt to display outline is deadly :)

**Comment by mniewrzal** [comment] 2016-11-25 14:13
Another problem is that simple refreshing 4k elements takes some time (300 ms in my case). I see two options at the moment:
* calculate changes between last and new list of symbols and build some kind of delta to refresh only changed elements
* try using VIRTUAL tree (I'm not sure if its possible with CNF)

**Comment by mickaelistria** [comment] 2016-11-28 08:44
I think it's still because of bad code: too many iterations (in each getParent, getChildren...). We should build the tree model when retrieving symbols and just access it rather than recomputing everytime.

**Comment by mniewrzal** [comment] 2016-11-28 08:49
Yeap :)

**Comment by mniewrzal** [comment] 2016-11-28 09:52
Do you plan to work with this or I can give it a try?

**Comment by mickaelistria** [comment] 2016-11-28 10:08
If you're interested in giving a try, feel free ;) I'm a bit busy with the legal part and a few related things in Platform at the moment, so if you're available to work on it, that's for sure be welcome.

**Comment by mniewrzal** [comment] 2016-11-30 13:42
https://bugs.eclipse.org/bugs/show_bug.cgi?id=508440

**Comment by mickaelistria** [comment] 2016-11-30 14:34
Closing as it's ported to Bugzilla (https://bugs.eclipse.org/bugs/show_bug.cgi?id=508440 )

**Closed as completed by mickaelistria** 2016-11-30 14:34 UTC
Labels: bug
